import { URL } from "../../../../../Setup";

export const API = {
    LIQUIDAR_FATURA: `${URL}/mk/WSMKCRLiquidarFaturas.rule`,
    ESTORNAR_FATURA: `${URL}/mk/WSMKEstornarFaturas.rule`,
    SUSPENDER_FATURA: `${URL}/mk/WSMKCRSuspenderFatura.rule`,
    REMOVER_SUSPENSAO_FATURA: `${URL}/mk/WSMKCRRemoverSuspensaoFatura.rule`,
    GERAR_COBRANCA_PIX: `${URL}/mk/WSMKCRGerarCobrancaPixPost.rule`,
    GERAR_NOVO_EMAIL: `${URL}/mk/WSMKCRNovoEmail.rule`,
    INSERIR_ANEXO: `${URL}/mk/WSMKCPFaturaInserirAnexo.rule`,
    ADICIONAR_SPC: `${URL}/mk/WSMKCRInscreverSPC.rule`,
    ALTERAR_DETALHES_FATURA: `${URL}/mk/WSMKCREditarFatura.rule`,
    IMPRIMIR_RECIBO: `${URL}/mk/WSMKCRFaturaRecibo.rule`,
    IMPRIMIR_FATURA: `${URL}/mk/WSMKCRImpressaoMassa.rule`,
    ADICIONAR_COBRANCA_CARTAO: `${URL}/mk/WSMKCRInclCobrAdc.rule`,
    DAR_BAIXA_FATURA: `${URL}/mk/WSMKCRBaixarFatura.rule`,
    EXCLUIR_FATURA: `${URL}/mk/WSMKCRFaturaExcluir.rule`,
    LIQUIDAR_FATURAS_MASSA: `${URL}/mk/WSMKCRLiquidarFaturas.rule`,
    ESTORNAR_FATURAS_MASSA: `${URL}/mk/WSMKEstornarFaturas.rule`,
    SUSPENDER_FATURAS_MASSA: `${URL}/mk/WSMKCRSuspenderFatura.rule`,
    REMOVER_SUSPENSAO_FATURAS_MASSA: `${URL}/mk/WSMKCRRemoverSuspensaoFatura.rule`,
    IMPRESSAO_MASSA: `${URL}/mk/WSMKCRImpressaoMassa.rule`,
    INCLUIR_REMOVER_MARCACAO_REMESSA: `${URL}/mk/WSMKCRIncluirRemoverMarcacaoRemessa.rule`,
    FATURAS_GRADE: `${URL}/mk/WSMKCRFaturasReceber.rule`,
    EDITAR_CONTA: `${URL}/mk/WSMKCREditarConta.rule`,
    FATURAR_CONTA: `${URL}/mk/WSMKCRFaturarContas.rule`,
    SUSPENDER_CONTA: `${URL}/mk/WSMKCRSuspenderConta.rule`,
    REMOVER_SUSPENSAO_CONTA: `${URL}/mk/WSMKCRRemoverSuspensaoConta.rule`,
    CRIAR_NOVA_CONTA: `${URL}/mk/WSMKCRNovaConta.rule`,
    REMOVER_CONTA: `${URL}/mk/WSMKCRContaRemocao.rule`,
    ENVIAR_EMAILS_MASSA: `${URL}/mk/WSMKCREnvioEmailMassa.rule`,
    PERMITIR_IMPRESSAO: `${URL}/mk/WSMKCRConsiderarDesconsiderarImpressao.rule`,
    REMOVER_LOTE: `${URL}/mk/WSMKCRRemoverLote.rule`,
    PAGINA_EMAIL: `${URL}/mk/WSMKCREmailsInfoAcoes.rule`,
    PAGINA_EMAIL2: `${URL}/mk/WSMKCREmails.rule`,
    NOVO_LOTE_FATURAS: `${URL}/mk/WSMKCRNovoLoteFaturas.rule`,
    IMPRESSAO_GRADE_EMAIL: `blob:${URL}`,
};