on:
  push:
    branches:
      - main
jobs:
  tests_e2e:
    name: Run end-to-end tests
    runs-on: ubuntu-latest
    env:
      USER: ${{ secrets.USER }}
      USER_2: ${{ secrets.USER_2 }}
      PASSWORD: ${{ secrets.PASSWORD }}
      PASSWORD_2: ${{ secrets.PASSWORD_2 }}
      API_URL: ${{ secrets.API_URL }}
      CI_WORKERS: 1;
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Install dependencies
        run: npm ci
      - name: Run Playwright tests
        uses: microsoft/playwright-github-action@v1.5.6
      - name: Install playwright browsers
        run: npx playwright install --with-deps
      - name: Run tests
        run: npx playwright test bot_antigo.spec.ts --reporter=list
      - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30