on:
  push:
    branches:
      - main
jobs:
  tests_e2e:
    env:
      USER: ${{ secrets.USER }}
      USER_2: ${{ secrets.USER_2 }}
      PASSWORD: ${{ secrets.PASSWORD }}
      PASSWORD_2: ${{ secrets.PASSWORD_2 }}
      API_URL: ${{ secrets.API_URL }}
      CI_WORKERS: ${{ secrets.CI_WORKERS }}
    name: Run end-to-end tests in Docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker Image
        run: docker build -t playwright-tests -f ./Dockerfile .
      - name: Run Tests in Docker
        run: |
          docker run \
          -e USER=${{ secrets.USER }} \
          -e USER_2=${{ secrets.USER_2 }} \
          -e PASSWORD=${{ secrets.PASSWORD }} \
          -e PASSWORD_2=${{ secrets.PASSWORD_2 }} \
          -e API_URL=${{ secrets.API_URL }} \
          -e CI_WORKERS=${{ secrets.CI_WORKERS }} \
          playwright-tests
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
